import {
  SALES_BRAIN_AGENT_VERSION,
  SALES_BRAIN_ANALYSIS_VERSION,
  SALES_BRAIN_DECISION_VERSION,
  SALES_BRAIN_REPLY_PROMPT_VERSION,
} from './catalog.js';

function cleanText(value = '', max = 500) {
  return String(value || '').replace(/\s+/g, ' ').trim().slice(0, max);
}

export function buildSalesBrainEventPayload({
  type = 'inbound_analysis',
  inputMessageId = '',
  analysis = {},
  previousSalesState = null,
  newSalesState = null,
  previousConversationMemory = null,
  newConversationMemory = null,
  previousCommercialProgress = null,
  newCommercialProgress = null,
  qualificationBefore = null,
  qualificationAfter = null,
  scoreBreakdown = {},
  leadScore = 0,
  conversationObjective = 'WAIT',
  nextBestAction = 'WAIT',
  reason = '',
  productStrategy = 'unknown',
  actionRisk = 'restricted',
  selectedAsset = null,
  assetRequired = false,
  readyForSales = false,
  humanRequired = false,
  deliveredAction = null,
  deliveredAt = null,
  routing = null,
  commercialSignals = null,
  suggestedReply = '',
  replyGenerationStatus = '',
  analysisUsage = null,
  replyUsage = null,
  model = '',
  replyModel = '',
  createdAt = new Date(),
} = {}) {
  const safeReplyStatus = cleanText(replyGenerationStatus || (suggestedReply ? 'ok' : 'empty'), 40);
  return {
    type,
    inputMessageId: cleanText(inputMessageId, 180),
    analysis,
    previousSalesState,
    newSalesState,
    previousConversationMemory,
    newConversationMemory,
    previousCommercialProgress,
    newCommercialProgress,
    qualificationBefore,
    qualificationAfter,
    scoreBreakdown,
    leadScore: Number(leadScore || 0),
    conversationObjective,
    nextBestAction,
    reason: cleanText(reason, 500),
    productStrategy,
    actionRisk,
    selectedAsset,
    assetRequired: Boolean(assetRequired),
    readyForSales: Boolean(readyForSales),
    humanRequired: Boolean(humanRequired),
    deliveredAction,
    deliveredAt,
    routing,
    commercialSignals,
    suggestedReply: cleanText(suggestedReply, 1200),
    replyGenerationStatus: safeReplyStatus,
    analysisUsage,
    replyUsage,
    sellerDecision: null,
    finalReply: '',
    status: safeReplyStatus === 'failed' ? 'failed' : (suggestedReply ? 'pending' : 'no_action'),
    model: cleanText(model || analysis?.model || '', 120),
    replyModel: cleanText(replyModel, 120),
    agentVersion: SALES_BRAIN_AGENT_VERSION,
    analysisVersion: SALES_BRAIN_ANALYSIS_VERSION,
    decisionVersion: SALES_BRAIN_DECISION_VERSION,
    replyPromptVersion: SALES_BRAIN_REPLY_PROMPT_VERSION,
    createdAt,
    updatedAt: createdAt,
  };
}
